[book]
title = "药娘的天空"
authors = ["乱世银娘"]
description = "《药娘的天空》精修版"
language = "zh-cn"

[output.html]
curly-quotes = true
additional-css = ["theme/style.css", "theme/navigation.css"]
no-section-label = true
header-link = false
git-repository-url = "https://github.com/Zh40Le1ZOOB/YaoNiangDeTianKong-Fix"
edit-url-template = "https://github.com/Zh40Le1ZOOB/YaoNiangDeTianKong-Fix/edit/main/{path}"
site-url = "/YaoNiangDeTianKong-Fix/"

[output.html.fold]
enable = true

[output.html.search]
limit-results = 1000
